apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsiYXV0aCI6IlVHOXNhVzVoZG1Gek9UVTZaMmh3WDBwTGNGQlJVVmR0YkdSbFozUjBZbkJGYVdkNlNuTTVSbHBXU1VkR2FESjRSV1U1VWc9PSJ9fX0K

type: kubernetes.io/dockerconfigjson
